config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  get 'projects/:id/init', to: 'projects#init'
  get 'projects/:id/companion', to: 'projects#companion'
  root 'workflows#index'
  resources :projects
  resources :travel_companion_appearances
  resources :travel_companions
  resources :workflow_stages
  resources :workflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workflow.rb
class Workflow < ApplicationRecord
  has_and_belongs_to_many :workflow_stages, inverse_of: :workflow
  accepts_nested_attributes_for :workflow_stages,
    :allow_destroy => true,
    :reject_if     => :all_blank
end

app/controllers/workflows_controller.rb
  class WorkflowsController < ApplicationController
  before_action :set_workflow, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /workflows
  # GET /workflows.json
  def index
    @workflows = Workflow.all
  end

  # GET /workflows/1
  # GET /workflows/1.json
  def show
  end

  # GET /workflows/new
  def new
    @workflow = Workflow.new
    @workflow.workflow_stages.build
  end

  # GET /workflows/1/edit
  def edit
  end

  # POST /workflows
  # POST /workflows.json
  def create
    @workflow = Workflow.new(workflow_params)

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to @workflow, notice: 'Workflow was successfully created.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflows/1
  # PATCH/PUT /workflows/1.json
  def update
    respond_to do |format|
      if @workflow.update(workflow_params)
        format.html { redirect_to @workflow, notice: 'Workflow was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow }
      else
        format.html { render :edit }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflows/1
  # DELETE /workflows/1.json
  def destroy
    @workflow.destroy
    respond_to do |format|
      format.html { redirect_to workflows_url, notice: 'Workflow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow
      @workflow = Workflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_params
      params.require(:workflow).permit(:name, :description, workflow_stages_attributes: [:id, :name, :description, :position, :_destroy])
    end
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/workflows/_form.html.erb
<%= form_with(model: workflow, local: true) do |form| %>
<% if workflow.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(workflow.errors.count, "error") %> prohibited this workflow from being saved:</h2>

  <ul>
    <% workflow.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="input-field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :workflow_name %>
</div>

<div class="input-field">
  <%= form.text_area :description, id: :workflow_description, class: 'materialize-textarea' %>
  <%= form.label :description %>
</div>
<div class="row valign-wrapper">
<div class="col s6">
<h2>Stages</h2>
</div>
<div class="col s6">
      <%= link_to_add_association "Add stage", form, :workflow_stages, class: "btn waves-effect waves-light right", data: {association_insertion_node: "#list-stage", association_insertion_method: :append } %>
      </div>
    </div>


<ul id="list-stage" class="collection">
  <%= form.fields_for :workflow_stages do |form_stage| %>
  <%= render 'workflow_stage_fields', :f => form_stage %>
  <% end %>
</ul>


<div class="actions">
  <button class="btn waves-effect waves-light right" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
</div>
<% end %>

app/views/workflows/_workflow_stage_fields.html.erb
<li class="collection-item stage-list-item">
  <div class="row">
      <div class="input-field col s5">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="input-field col s5">
        <%= f.label :default_description %>
        <%= f.text_area :default_description, class: 'materialize-textarea' %>
      </div>
      <div class="input-field col s2">
      <%= f.hidden_field :position, class: 'workflow_workflow_stages_attributes_position' %>
      <%= f.hidden_field :id , class: 'workflow_workflow_stages_attributes_id' %>
      <%= link_to_remove_association "Remove", f,  class: "btn waves-effect waves-light red lighten-2" %>
      </div>
    </div>
</li>

app/views/workflows/edit.html.erb
<h1>Editing Workflow</h1>

<%= render 'form', workflow: @workflow %>

<%= link_to 'Show', @workflow %> |
<%= link_to 'Back', workflows_path %>

app/views/workflows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workflows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflows.each do |workflow| %>
      <tr>
        <td><%= workflow.name %></td>
        <td><%= workflow.description %></td>
        <td><%= link_to 'Show', workflow %></td>
        <td><%= link_to 'Edit', edit_workflow_path(workflow) %></td>
        <td><%= link_to 'Destroy', workflow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow', new_workflow_path %>

app/views/workflows/new.html.erb
<h1>New Workflow</h1>

<%= render 'form', workflow: @workflow %>

<%= link_to 'Back', workflows_path, class: "btn waves-effect waves-light lighten-2 teal" %>

app/views/workflows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workflow.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workflow.description %>
</p>

<% for workflow_stage in @workflow.workflow_stages %>
<%= workflow_stage.name %>
<% end %>

<%= link_to 'Edit', edit_workflow_path(@workflow) %> |
<%= link_to 'Back', workflows_path, class: "btn waves-effect waves-light lighten-5"%>