config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  get 'projects/:id/init', to: 'projects#init'
  get 'projects/:id/companion', to: 'projects#companion'
  root 'workflows#index'
  resources :projects
  resources :travel_companion_appearances
  resources :travel_companions
  resources :workflow_stages
  resources :workflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workflow_stage.rb
class WorkflowStage < ApplicationRecord
  has_and_belongs_to_many :workflows
  default_scope { order(:position) }
end

app/controllers/workflow_stages_controller.rb
class WorkflowStagesController < ApplicationController
  before_action :set_workflow_stage, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /workflow_stages
  # GET /workflow_stages.json
  def index
    @workflow_stages = WorkflowStage.all
  end

  # GET /workflow_stages/1
  # GET /workflow_stages/1.json
  def show
  end

  # GET /workflow_stages/new
  def new
    @workflow_stage = WorkflowStage.new
  end

  # GET /workflow_stages/1/edit
  def edit
  end

  # POST /workflow_stages
  # POST /workflow_stages.json
  def create
    @workflow_stage = WorkflowStage.new(workflow_stage_params)

    respond_to do |format|
      if @workflow_stage.save
        format.html { redirect_to @workflow_stage, notice: 'Workflow stage was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_stage }
      else
        format.html { render :new }
        format.json { render json: @workflow_stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_stages/1
  # PATCH/PUT /workflow_stages/1.json
  def update
    respond_to do |format|
      if @workflow_stage.update(workflow_stage_params)
        format.html { redirect_to @workflow_stage, notice: 'Workflow stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_stage }
      else
        format.html { render :edit }
        format.json { render json: @workflow_stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_stages/1
  # DELETE /workflow_stages/1.json
  def destroy
    @workflow_stage.destroy
    respond_to do |format|
      format.html { redirect_to workflow_stages_url, notice: 'Workflow stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_stage
      @workflow_stage = WorkflowStage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_stage_params
      params.require(:workflow_stage).permit(:name, :description)
    end
end

app/helpers/workflow_stages_helper.rb
module WorkflowStagesHelper
end

app/views/workflow_stages/_form.html.erb
<%= form_with(model: workflow_stage, local: true) do |form| %>
  <% if workflow_stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workflow_stage.errors.count, "error") %> prohibited this workflow_stage from being saved:</h2>

      <ul>
      <% workflow_stage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :workflow_stage_name %>
  </div>

  <div class="field">
    <%= form.label :default_description %>
    <%= form.text_area :default_description, id: :workflow_stage_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workflow_stages/edit.html.erb
<h1>Editing Workflow Stage</h1>

<%= render 'form', workflow_stage: @workflow_stage %>

<%= link_to 'Show', @workflow_stage %> |
<%= link_to 'Back', workflow_stages_path %>

app/views/workflow_stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workflow Stages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Default Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_stages.each do |workflow_stage| %>
      <tr>
        <td><%= workflow_stage.name %></td>
        <td><%= workflow_stage.default_description %></td>
        <td><%= link_to 'Show', workflow_stage %></td>
        <td><%= link_to 'Edit', edit_workflow_stage_path(workflow_stage) %></td>
        <td><%= link_to 'Destroy', workflow_stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow Stage', new_workflow_stage_path %>

app/views/workflow_stages/new.html.erb
<h1>New Workflow Stage</h1>

<%= render 'form', workflow_stage: @workflow_stage %>

<%= link_to 'Back', workflow_stages_path %>

app/views/workflow_stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workflow_stage.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workflow_stage.default_description %>
</p>

<%= link_to 'Edit', edit_workflow_stage_path(@workflow_stage) %> |
<%= link_to 'Back', workflow_stages_path %>