config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  get 'projects/:id/init', to: 'projects#init'
  get 'projects/:id/companion', to: 'projects#companion'
  root 'workflows#index'
  resources :projects
  resources :travel_companion_appearances
  resources :travel_companions
  resources :workflow_stages
  resources :workflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :workflow
  belongs_to :travel_companion, optional: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @projects = Project.all
  end

  # GET /projects/1/init
  def init
    @project = Project.find(params[:id])
  end

  # GET /projects/1/init
  def companion
    @project = Project.find(params[:id])
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :stages, :workflow_id, :travel_companion_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :workflow_id %>
    <div class="input-field col s12 m6">
      <select name="project[workflow_id]">
      <% workflows_array = Workflow.all.map { |workflow| [workflow.name, workflow.id] } %>

        <option value="" disabled selected>Workflow</option>
        <%= options_for_select(workflows_array) %>
      </select>

    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/companion.html.erb
<style>
.wrap {
  background: #1b30a4;
}
.title-wrap {
  position: relative;
  text-align: center;
  font-family: 'MuseoSans';
  color: white;
  text-transform: uppercase;
  font-size: 30px;
  line-height: 180px;
}
.title-wrap > div {
  text-align: center;
  width: 100%;
  top: 0;
  color: rgba(22, 163, 254, 0.06);
  font-size: 120px;
  position: absolute;
}
.nav-wrapper, nav {
  background-color: transparent;
  box-shadow: none;
}
.select-wrapper {
  background-color: white;
}
</style>
<div class='row'>
  <div class='col m6 offset-m3'>
    <div class='title-wrap'>
      Choose your travel companion
    <div>Travel</div>
    <div>
  </div>
</div>
<div class='row'>
  <%= form_with model: @project do |form| %>
  <select name='project[travel_companion_id]' class='icons'>
  <% travel_companion_array = TravelCompanion.all.map { |companion| [companion.name, companion.id] } %>
    <option value='' disabled selected>Companion</option>
    <%= options_for_select(travel_companion_array) %>
  </select>
  <%= form.submit "Choisir", :class => "waves-effect waves-light btn-small" %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stages</th>
      <th>Workflow</th>
      <th>Travel companion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.stages %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Init', controller: "projects", action: "init", id: project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/init.html.erb
<style>
.background-square {
  top: 0;
  z-index: -30;
  width: 100%;
  height: 300px;
  background-image: linear-gradient(to bottom right, #290075 0%, #086ddf 100%);
}
.background-radius {
  z-index: -10;
  border-radius: 50px;
  top: 0;
  width: 100%;
  height: 400px;
  transform: rotate(1deg);
}
.background-white {
  background-color: white;
  position: absolute;
  top: 200px;
  width: 100%;
  z-index: -20;
  height: 300px;
}

.background {
  position: absolute;
  background-image: linear-gradient(to bottom right, #290075 0%, #086ddf 100%);
  background-size: cover;
  background-repeat: no-repeat;
}
.nav-wrapper, nav {
  background-color: transparent;
  box-shadow: none;
}
h1 {
  margin-top: 84px;
  color: white;
}
.welcome-message {
  margin-top: 150px;
  font-size: 20px;
}
</style>
<script>
  $( "#other" ).click(function() {
    $( "#target" ).click();
  });
</script>
<div style='top: 0; position: absolute; overflow: hidden; width: 100%; height: 500px;'>
<div class='background-square background'></div>
<div class='background-radius background'></div>
<div class='background-white'></div>
</div>
<div class='row'>
  <div class='col s6 offset-s1'>
    <h1>Revolutionize the customer service</h1>
  </div>
  <div class='col s4' style='margin-top: 64px;'>
      <div class='card z-depth-3'>
        <div class='card-content'>
          <span class='card-title'><%= @project.name %></span>
          <p><%= @project.description %></p>
          <a href='<%= url_for :controller => 'projects', :action => 'companion', :id => @project.id %>' class='waves-effect waves-light btn-large' style='margin-top: 30px; width: 100%; background-image: linear-gradient(to right, #41faa4 0%, #16a3fe 100%);'>
            Let's go
          </a>
        </div>
      </div>
    </div>
</div>
<div class='row welcome-message'>
  <div class='col m6 offset-m1'>
    Monitor and follow your project.<br>
    Keep informed.<br>
    Love the experience.
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
 <% progress = 0
if @project.stages > 0
  progress = (@project.stages.to_f / @project.workflow.workflow_stages.size.to_f * 100).round
end %>
<style>
.wrap {
  background: #1b30a4;
}
.nav-wrapper, nav {
  background-color: transparent;
  box-shadow: none;
}
</style>
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col s12 m4 offset-m1'>
    <div class='card z-depth-3'>
      <div class='card-content'>
        <span class='card-title'><%= @project.name %></span>
        <p>
          <%= @project.workflow.name %><br>
          <%= @project.description %>
        </p>
      </div>
      <div class="card-action">
        <p style="margin: 0; text-align: center;"><%= progress %> %</p>
        <div class="progress" style="height: 5px;">
          <div class="determinate" style="width: <%= progress %>%;  background-image: linear-gradient(to right, #41faa4 0%, #16a3fe 100%);"></div>
        </div>
      </div>

    </div>
  </div>




  <div class='col s12 m2'>
    <% if company_signed_in? %>
    <div class="row">
      <%= form_with model: @project do |form| %>
      <%= form.hidden_field :stages, :value => @project.stages-1 %>
      <%= form.submit "Annuler l'étape", :class => "waves-effect waves-light btn-small" %>
      <% end %>
    </div>
    <div class="row">
      <%= form_with model: @project do |form| %>
      <%= form.hidden_field :stages, :value => @project.stages+1 %>
      <%= form.submit "Valider l'étape", :class => "waves-effect waves-light btn-small" %>
      <% end %>
    </div>
    <div class="row">
      <%= form_with model: @project do |form| %>
      <%= form.hidden_field :action_required, :value => 1 %>
      <%= form.submit "Action requise", :class => "waves-effect waves-light btn-small" %>
      <% end %>
    </div>
      <% end %>
  </div>


  <div class='col s12 m4'>
    <% if @project.travel_companion != nil %>
    <img class="tooltipped" data-position="right" data-tooltip="Je suis Léo.<br>
    Je vais droit au but.<br>
    Mon point fort: la rapidité." src="<%= @project.travel_companion.travel_companion_appearance.welcome_picture %>" alt="Companion" height="100" width="100">
  </a>
  <% end %>
  </div>
</div>



<div class='row'>
  <div class='col s12 m4 offset-m1'>
    <div class='card z-depth-3'>
      <div class='card-content'>
        <% stages = @project.workflow.workflow_stages %>
        <% @project.workflow.workflow_stages.each_with_index do |stage, index| %>
        <%= stage.name %><% if index < @project.stages %> ✅<% elsif index == @project.stages %> ⚙️<% end %><br>
        <% end %>
      </div>
    </div>
  </div>
</div>