config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  get 'projects/:id/init', to: 'projects#init'
  get 'projects/:id/companion', to: 'projects#companion'
  root 'workflows#index'
  resources :projects
  resources :travel_companion_appearances
  resources :travel_companions
  resources :workflow_stages
  resources :workflows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/travel_companion.rb
class TravelCompanion < ApplicationRecord
  belongs_to :travel_companion_appearance
  accepts_nested_attributes_for :travel_companion_appearance
end

app/controllers/travel_companions_controller.rb
class TravelCompanionsController < ApplicationController
  before_action :set_travel_companion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /travel_companions
  # GET /travel_companions.json
  def index
    @travel_companions = TravelCompanion.all
  end

  # GET /travel_companions/1
  # GET /travel_companions/1.json
  def show
  end

  # GET /travel_companions/new
  def new
    @travel_companion = TravelCompanion.new
  end

  # GET /travel_companions/1/edit
  def edit
  end

  # POST /travel_companions
  # POST /travel_companions.json
  def create
    @travel_companion = TravelCompanion.new(travel_companion_params)

    respond_to do |format|
      if @travel_companion.save
        format.html { redirect_to @travel_companion, notice: 'Travel companion was successfully created.' }
        format.json { render :show, status: :created, location: @travel_companion }
      else
        format.html { render :new }
        format.json { render json: @travel_companion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travel_companions/1
  # PATCH/PUT /travel_companions/1.json
  def update
    respond_to do |format|
      if @travel_companion.update(travel_companion_params)
        format.html { redirect_to @travel_companion, notice: 'Travel companion was successfully updated.' }
        format.json { render :show, status: :ok, location: @travel_companion }
      else
        format.html { render :edit }
        format.json { render json: @travel_companion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travel_companions/1
  # DELETE /travel_companions/1.json
  def destroy
    @travel_companion.destroy
    respond_to do |format|
      format.html { redirect_to travel_companions_url, notice: 'Travel companion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel_companion
      @travel_companion = TravelCompanion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_companion_params
      params.require(:travel_companion).permit(:name, :description, :expertise, :patience, :perfectionism, :ambition, :talkativeness, :travel_companion_appearance_id)
    end
end

app/helpers/travel_companions_helper.rb
module TravelCompanionsHelper
end

app/views/travel_companions/_form.html.erb
<%= form_with(model: travel_companion, local: true) do |form| %>
  <% if travel_companion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(travel_companion.errors.count, "error") %> prohibited this travel_companion from being saved:</h2>

      <ul>
      <% travel_companion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :travel_companion_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :travel_companion_description %>
  </div>

  <div class="field">
    <label>Travel Companion Apperance</label>
    <div class="input-field col s12 m6">
      <select name="travel_companion[travel_companion_appearance_id]" class="icons">
      <% travel_companion_appearances_array = TravelCompanionAppearance.all.map { |appearance| [appearance.name, appearance.id, {'data-icon' => appearance.profile_picture}] } %>

        <option value="" disabled selected>Appearance</option>
        <%= options_for_select(travel_companion_appearances_array) %>
      </select>

    </div>
  </div>

  <div class="field">
    <%= form.label :expertise %>
    <%= form.number_field :expertise, id: :travel_companion_expertise %>
  </div>

  <div class="field">
    <%= form.label :patience %>
    <%= form.number_field :patience, id: :travel_companion_patience %>
  </div>

  <div class="field">
    <%= form.label :perfectionism %>
    <%= form.number_field :perfectionism, id: :travel_companion_perfectionism %>
  </div>

  <div class="field">
    <%= form.label :ambition %>
    <%= form.number_field :ambition, id: :travel_companion_ambition %>
  </div>

  <div class="field">
    <%= form.label :talkativeness %>
    <%= form.number_field :talkativeness, id: :travel_companion_talkativeness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/travel_companions/edit.html.erb
<h1>Editing Travel Companion</h1>

<%= render 'form', travel_companion: @travel_companion %>

<%= link_to 'Show', @travel_companion %> |
<%= link_to 'Back', travel_companions_path %>

app/views/travel_companions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Travel Companions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Expertise</th>
      <th>Patience</th>
      <th>Perfectionism</th>
      <th>Ambition</th>
      <th>Talkativeness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @travel_companions.each do |travel_companion| %>
      <tr>
        <td><%= travel_companion.name %></td>
        <td><%= travel_companion.description %></td>
        <td><%= travel_companion.expertise %></td>
        <td><%= travel_companion.patience %></td>
        <td><%= travel_companion.perfectionism %></td>
        <td><%= travel_companion.ambition %></td>
        <td><%= travel_companion.talkativeness %></td>
        <td><%= link_to 'Show', travel_companion %></td>
        <td><%= link_to 'Edit', edit_travel_companion_path(travel_companion) %></td>
        <td><%= link_to 'Destroy', travel_companion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Travel Companion', new_travel_companion_path %>

app/views/travel_companions/new.html.erb
<h1>New Travel Companion</h1>

<%= render 'form', travel_companion: @travel_companion %>

<%= link_to 'Back', travel_companions_path %>

app/views/travel_companions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @travel_companion.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @travel_companion.description %>
</p>

<p>
  <strong>Expertise:</strong>
  <%= @travel_companion.expertise %>
</p>

<p>
  <strong>Patience:</strong>
  <%= @travel_companion.patience %>
</p>

<p>
  <strong>Perfectionism:</strong>
  <%= @travel_companion.perfectionism %>
</p>

<p>
  <strong>Ambition:</strong>
  <%= @travel_companion.ambition %>
</p>

<p>
  <strong>Talkativeness:</strong>
  <%= @travel_companion.talkativeness %>
</p>

<%= link_to 'Edit', edit_travel_companion_path(@travel_companion) %> |
<%= link_to 'Back', travel_companions_path %>